/*
  # Seed EM9_INT Daily Activities - Part 1 (Modules 1 & 2)

  1. New Data
    - `em_daily_activities`: ~30 activities for Modules 1 and 2
    - Covers days 1-10 for each module including performance tasks, FAL lessons, and assessments

  2. Notes
    - All resource_urls stored as JSONB with named keys (task_paper, full_lesson_slides, etc.)
    - Uses ON CONFLICT (activity_id) DO NOTHING for idempotency
*/

-- Module 1 Activities
INSERT INTO em_daily_activities (activity_id, level_code, module_id, subtopic_id, day_number, activity_type, prompt_text, resource_urls) VALUES
  ('em9int_m1_d1_logistics_00', 'EM9_INT', 'em9int_m1', NULL, 1, 'logistics', 'Norms / Pre-assessments / Logistics', '{}'::jsonb),
  ('em9int_m1_d2_performance_task_01', 'EM9_INT', 'em9int_m1', 'em9int_m1_s1', 2, 'performance_task', 'Modeling Expressions Task', '{"task_paper": "https://drive.google.com/file/d/1eHiwWnEOxPai9yTNQTonPVscvSv7Wb8L/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/15ZQnnFR4_in49-gtZWhRPXmybkrw_iDKg3y27vx-QiQ/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/11c0rrHfvrlK1Y6idWWK5yZBxb8Fif97B/view?usp=sharing", "student_paced_pdf": "https://drive.google.com/file/d/1W90Np4QEKGcSK1eKqUyTFFSynrx1SB4o/view?usp=sharing"}'::jsonb),
  ('em9int_m1_d2_fal_pre_assessment_02', 'EM9_INT', 'em9int_m1', 'em9int_m1_s2', 2, 'fal_pre_assessment', 'Pre-assessment for Interpreting Equations (FAL 1A)', '{"task_paper": "https://drive.google.com/file/d/14HyzJ2EQ1rga6w-RoozRxAGoSSW64DAk/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1YQEB2SxVseeYo7wGjqw-MoE_3gwMkrJykmJgNJ0xGAE/copy?usp=sharing"}'::jsonb),
  ('em9int_m1_d3_fal_pre_assessment_03', 'EM9_INT', 'em9int_m1', 'em9int_m1_s3', 3, 'fal_pre_assessment', 'Pre-assessment for Interpreting Algebraic Expressions (FAL 1B)', '{"task_paper": "https://drive.google.com/file/d/1bq0_kj2wEI1fMgpyC0pNNjxoyBdpiBCA/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1hctPpQHLfOgO1x2ofV_VXXzj8e7Wq_jjggvtwq5tFEo/copy?usp=sharing"}'::jsonb),
  ('em9int_m1_d3_fal_lesson_04', 'EM9_INT', 'em9int_m1', 'em9int_m1_s2', 3, 'fal_lesson', 'Launch — Interpreting Equations (1 of 3)', '{"task_paper": "https://drive.google.com/file/d/1136eExpmp_p2oG7Mo0Yxmoz3vU2IhVOT/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1YQEB2SxVseeYo7wGjqw-MoE_3gwMkrJykmJgNJ0xGAE/copy?usp=sharing"}'::jsonb),
  ('em9int_m1_d4_fal_lesson_05', 'EM9_INT', 'em9int_m1', 'em9int_m1_s2', 4, 'fal_lesson', 'Interpreting Equations (2 of 3)', '{"task_paper": "https://drive.google.com/file/d/1136eExpmp_p2oG7Mo0Yxmoz3vU2IhVOT/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1YQEB2SxVseeYo7wGjqw-MoE_3gwMkrJykmJgNJ0xGAE/copy?usp=sharing"}'::jsonb),
  ('em9int_m1_d5_fal_lesson_06', 'EM9_INT', 'em9int_m1', 'em9int_m1_s2', 5, 'fal_lesson', 'Interpreting Equations (3 of 3)', '{"task_paper": "https://drive.google.com/file/d/1136eExpmp_p2oG7Mo0Yxmoz3vU2IhVOT/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1YQEB2SxVseeYo7wGjqw-MoE_3gwMkrJykmJgNJ0xGAE/copy?usp=sharing"}'::jsonb),
  ('em9int_m1_d5_fal_post_assessment_07', 'EM9_INT', 'em9int_m1', 'em9int_m1_s2', 5, 'fal_post_assessment', 'Post-assessment for Interpreting Equations', '{"task_paper": "https://drive.google.com/file/d/14HyzJ2EQ1rga6w-RoozRxAGoSSW64DAk/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1YQEB2SxVseeYo7wGjqw-MoE_3gwMkrJykmJgNJ0xGAE/copy?usp=sharing"}'::jsonb),
  ('em9int_m1_d6_fal_lesson_08', 'EM9_INT', 'em9int_m1', 'em9int_m1_s3', 6, 'fal_lesson', 'Interpreting Algebraic Expressions (Core FAL)', '{"task_paper": "https://drive.google.com/file/d/1bq0_kj2wEI1fMgpyC0pNNjxoyBdpiBCA/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1hctPpQHLfOgO1x2ofV_VXXzj8e7Wq_jjggvtwq5tFEo/copy?usp=sharing"}'::jsonb),
  ('em9int_m1_d6_fal_lesson_09', 'EM9_INT', 'em9int_m1', 'em9int_m1_s3', 6, 'fal_lesson', 'Interpreting Algebraic Expressions (1 of 3)', '{"task_paper": "https://drive.google.com/file/d/1bq0_kj2wEI1fMgpyC0pNNjxoyBdpiBCA/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1hctPpQHLfOgO1x2ofV_VXXzj8e7Wq_jjggvtwq5tFEo/copy?usp=sharing"}'::jsonb),
  ('em9int_m1_d7_fal_lesson_10', 'EM9_INT', 'em9int_m1', 'em9int_m1_s3', 7, 'fal_lesson', 'Interpreting Algebraic Expressions (2 of 3)', '{"task_paper": "https://drive.google.com/file/d/1bq0_kj2wEI1fMgpyC0pNNjxoyBdpiBCA/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1hctPpQHLfOgO1x2ofV_VXXzj8e7Wq_jjggvtwq5tFEo/copy?usp=sharing"}'::jsonb),
  ('em9int_m1_d8_fal_lesson_11', 'EM9_INT', 'em9int_m1', 'em9int_m1_s3', 8, 'fal_lesson', 'Interpreting Algebraic Expressions (3 of 3)', '{"task_paper": "https://drive.google.com/file/d/1bq0_kj2wEI1fMgpyC0pNNjxoyBdpiBCA/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1hctPpQHLfOgO1x2ofV_VXXzj8e7Wq_jjggvtwq5tFEo/copy?usp=sharing"}'::jsonb),
  ('em9int_m1_d8_fal_post_assessment_12', 'EM9_INT', 'em9int_m1', 'em9int_m1_s3', 8, 'fal_post_assessment', 'Post-assessment for Interpreting Algebraic Expressions', '{"task_paper": "https://drive.google.com/file/d/1bq0_kj2wEI1fMgpyC0pNNjxoyBdpiBCA/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1hctPpQHLfOgO1x2ofV_VXXzj8e7Wq_jjggvtwq5tFEo/copy?usp=sharing"}'::jsonb),
  ('em9int_m1_d8_performance_task_13', 'EM9_INT', 'em9int_m1', 'em9int_m1_s4', 8, 'performance_task', 'Matching Cards Task', '{"task_paper": "https://docs.google.com/presentation/d/1_syV99hZnRSTvk8ADdKsPIbPd-uXWqBjgkfS-eQUb5w/copy?usp=sharing", "task_pdf": "https://drive.google.com/file/d/1RdkCBHR1JsFclKa7tvHaQqhHSnO6Yl0X/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/1_syV99hZnRSTvk8ADdKsPIbPd-uXWqBjgkfS-eQUb5w/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1uOTTLhOfMlkNh2b1Gha_e5PNfayoqfYK/view?usp=sharing"}'::jsonb),
  ('em9int_m1_d9_performance_task_14', 'EM9_INT', 'em9int_m1', 'em9int_m1_s4', 9, 'performance_task', 'It is Just An Expression Task', '{"task_paper": "https://drive.google.com/file/d/11_L20tHVb-L4JEmuCqGzYAJFdHsKnQZ0/view?usp=sharing", "task_pdf": "https://drive.google.com/file/d/1-yWvYZ61RnEAgJ8O5tBu4RjlLtiHcmSF/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/1eXwwcMhh6xsMZSevCY9RRXUIKmoEVCvz2XLGyJ2o_-g/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1A1yjq83PwSf_-HTrYbDbEzkZ4drVqwVT/view?usp=sharing"}'::jsonb)
ON CONFLICT (activity_id) DO NOTHING;

-- Module 2 Activities
INSERT INTO em_daily_activities (activity_id, level_code, module_id, subtopic_id, day_number, activity_type, prompt_text, resource_urls) VALUES
  ('em9int_m2_d1_fal_pre_assessment_00', 'EM9_INT', 'em9int_m2', 'em9int_m2_s1', 1, 'fal_pre_assessment', 'Pre-assessment for Generating Patterns — Table Tiles (FAL 2)', '{"task_paper": "https://drive.google.com/file/d/1NSNioAtpXrwMNgCBVnpa4svtwuoE__kw/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1o3_ZbGJDspF4tPD1n8R5dt_OAD4uyLIucFs4PnbGun8/copy?usp=sharing", "student_pages_printable": "https://drive.google.com/file/d/1xoSM38FJUnELF-jvfh5ez2g2MmbPWUq8/view?usp=sharing"}'::jsonb),
  ('em9int_m2_d1_performance_task_01', 'EM9_INT', 'em9int_m2', 'em9int_m2_s2', 1, 'performance_task', 'Vertical Slice (Choice of 6 Tasks — Students do at least 3)', '{"vertical_slice_tasks": "https://drive.google.com/file/d/1WvuXaVZ_04__LqLKyeJk7TkgsemtquBP/view?usp=sharing", "plenary_lesson_slides": "https://docs.google.com/presentation/d/1GQHj_NEbxM578jSgp1ZHM8af5GncSGykrEwhHth_BWc/copy?usp=sharing", "plenary_lesson_pdf": "https://drive.google.com/file/d/1TNP5Iz309RmcA1AdYJiyg_KEQcKgqAxh/view?usp=sharing", "vertical_slice_nearpod": "https://docs.google.com/presentation/d/1faGPgG2lPhgPcINneUNWlm0-akusfaHsyHJUPWm_ok4/copy?usp=sharing"}'::jsonb),
  ('em9int_m2_d2_plenary_discussion_02', 'EM9_INT', 'em9int_m2', 'em9int_m2_s2', 2, 'plenary_discussion', 'Plenary discussion — choose 3 from Vertical Slice (1 at grade level)', '{"vertical_slice_tasks": "https://drive.google.com/file/d/1WvuXaVZ_04__LqLKyeJk7TkgsemtquBP/view?usp=sharing", "plenary_lesson_slides": "https://docs.google.com/presentation/d/1GQHj_NEbxM578jSgp1ZHM8af5GncSGykrEwhHth_BWc/copy?usp=sharing", "plenary_lesson_pdf": "https://drive.google.com/file/d/1TNP5Iz309RmcA1AdYJiyg_KEQcKgqAxh/view?usp=sharing", "vertical_slice_nearpod": "https://docs.google.com/presentation/d/1faGPgG2lPhgPcINneUNWlm0-akusfaHsyHJUPWm_ok4/copy?usp=sharing"}'::jsonb),
  ('em9int_m2_d3_performance_task_03', 'EM9_INT', 'em9int_m2', 'em9int_m2_s3', 3, 'performance_task', 'Trapezoidal Numbers (2001)', '{"task_paper": "https://drive.google.com/file/d/16G6SaV4qgkr04-VJr_JK73rrBnLdQ1KK/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/1H2e3lWBev899ubvKbaLfcuBhlLu0pYNu09PjJM3m2Cs/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/16G6SaV4qgkr04-VJr_JK73rrBnLdQ1KK/view?usp=sharing", "student_paced": "https://docs.google.com/presentation/d/1dqzcU9lOlwXM17vk67nD3ow79XcDVQC-eJkQXlxFs5E/copy?usp=sharing"}'::jsonb),
  ('em9int_m2_d4_performance_task_04', 'EM9_INT', 'em9int_m2', 'em9int_m2_s3', 4, 'performance_task', 'End of Year Dinner', '{"task_paper": "https://drive.google.com/file/d/1aB0Ycu63QtqHsl_uSrtnnl25zMCNWXG6/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/12pv3kxt0DVCMu-RGzRnGYIzdRqnw3QHU3IvQ_EHkCZU/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1aB0Ycu63QtqHsl_uSrtnnl25zMCNWXG6/view?usp=sharing", "student_paced": "https://docs.google.com/presentation/d/1sV3vpomxM_mbAcNbgwKUNsqO1H4Jw9_Rq7jgmsalU4w/copy?usp=sharing"}'::jsonb),
  ('em9int_m2_d5_performance_task_05', 'EM9_INT', 'em9int_m2', 'em9int_m2_s3', 5, 'performance_task', 'Patrick''s Patterns', '{"task_paper": "https://drive.google.com/file/d/120mJdbyfNTMN41baQ5LmaxcxUj6PUoJ1/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/1JS3j72gmujxpT2t88aHpoi5odJrnvIOOABC3bE4FGM8/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1Z-Nhw24HQs8ocUdiDhu8MIXZSrmP1fXu/view?usp=sharing", "student_paced": "https://docs.google.com/presentation/d/1DA3RmIkVS_b6fQEMg8bBovxqm4gW5pPWhipFkLzX5Yo/copy?usp=sharing"}'::jsonb),
  ('em9int_m2_d6_fal_lesson_06', 'EM9_INT', 'em9int_m2', 'em9int_m2_s1', 6, 'fal_lesson', 'Generalizing Patterns: Table Tiles (Day 1 of 3)', '{"task_paper": "https://drive.google.com/file/d/1NSNioAtpXrwMNgCBVnpa4svtwuoE__kw/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1o3_ZbGJDspF4tPD1n8R5dt_OAD4uyLIucFs4PnbGun8/copy?usp=sharing"}'::jsonb),
  ('em9int_m2_d7_fal_lesson_07', 'EM9_INT', 'em9int_m2', 'em9int_m2_s1', 7, 'fal_lesson', 'Generalizing Patterns: Table Tiles (Day 2 of 3)', '{"task_paper": "https://drive.google.com/file/d/1NSNioAtpXrwMNgCBVnpa4svtwuoE__kw/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1o3_ZbGJDspF4tPD1n8R5dt_OAD4uyLIucFs4PnbGun8/copy?usp=sharing"}'::jsonb),
  ('em9int_m2_d8_fal_lesson_08', 'EM9_INT', 'em9int_m2', 'em9int_m2_s1', 8, 'fal_lesson', 'Generalizing Patterns: Table Tiles (Day 3 of 3)', '{"task_paper": "https://drive.google.com/file/d/1NSNioAtpXrwMNgCBVnpa4svtwuoE__kw/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1o3_ZbGJDspF4tPD1n8R5dt_OAD4uyLIucFs4PnbGun8/copy?usp=sharing"}'::jsonb),
  ('em9int_m2_d8_fal_post_assessment_09', 'EM9_INT', 'em9int_m2', 'em9int_m2_s1', 8, 'fal_post_assessment', 'Post-assessment for Generating Patterns: Table Tiles', '{"task_paper": "https://drive.google.com/file/d/1NSNioAtpXrwMNgCBVnpa4svtwuoE__kw/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1o3_ZbGJDspF4tPD1n8R5dt_OAD4uyLIucFs4PnbGun8/copy?usp=sharing", "student_pages_printable": "https://drive.google.com/file/d/1xoSM38FJUnELF-jvfh5ez2g2MmbPWUq8/view?usp=sharing"}'::jsonb),
  ('em9int_m2_d9_performance_task_10', 'EM9_INT', 'em9int_m2', 'em9int_m2_s4', 9, 'performance_task', 'Linda''s Tiles', '{"task_paper": "https://drive.google.com/file/d/1wS6MG4f_S_3VJmQKhZkMHbp4c8cSLd_S/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/1g3W-nAq7_SdfsETgMKhwGvYoI2e8CD-xFd6AK38TL3Q/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1hnTrZ4EuhmzEcEmHthR5Gg1BCkLz2dZx/view?usp=sharing", "student_paced": "https://docs.google.com/presentation/d/108h0IOy8D3rQ5hFJB5fFvNWbgRoIsnYSDfkd5bSDV_Q/copy?usp=sharing"}'::jsonb),
  ('em9int_m2_d10_post_assessment_11', 'EM9_INT', 'em9int_m2', NULL, 10, 'post_assessment', 'Grade 9 post-assessment (if only completing modules 1 and 2)', '{"faculty_portal": "http://svef.force.com/faculty", "assessment_tab_slides": "https://docs.google.com/presentation/d/18xqcFMXz8FAc2AKlHbFZgd-2ANgv23AAMWySVZc_SrY/copy?usp=sharing"}'::jsonb),
  ('em9int_m2_vertical_slice_00', 'EM9_INT', 'em9int_m2', 'em9int_m2_s2', NULL, 'vertical_slice_task', 'Piles of Oranges', '{}'::jsonb),
  ('em9int_m2_vertical_slice_01', 'EM9_INT', 'em9int_m2', 'em9int_m2_s2', NULL, 'vertical_slice_task', 'Bead Necklaces', '{}'::jsonb),
  ('em9int_m2_vertical_slice_02', 'EM9_INT', 'em9int_m2', 'em9int_m2_s2', NULL, 'vertical_slice_task', 'Necklaces', '{"task": "https://drive.google.com/file/d/1nKLHB1oDBJ1G-u0c10clHIhoc6U6ZCB7/view?usp=sharing", "rubric": "https://drive.google.com/file/d/1OAlQ9gIf0BuRUiNrH-FuUK4ZMxdwThjb/view?usp=sharing"}'::jsonb),
  ('em9int_m2_vertical_slice_03', 'EM9_INT', 'em9int_m2', 'em9int_m2_s2', NULL, 'vertical_slice_task', 'Grocery Store Cart', '{"task": "https://drive.google.com/file/d/1r7YPn-OLpbCcHZtcXJyFARJAI9ZkEJ8M/view?usp=sharing", "rubric": "https://drive.google.com/file/d/1k-H4ZbYI1C1Ic7Sl-8MQH6e56G9l2L4F/view?usp=sharing"}'::jsonb),
  ('em9int_m2_vertical_slice_04', 'EM9_INT', 'em9int_m2', 'em9int_m2_s2', NULL, 'vertical_slice_task', 'Toothpick Stairs', '{"task": "https://drive.google.com/file/d/1T9qXpPPBlhjVMZH-vt7rXD0_FivgHmrc/view?usp=sharing", "rubric": "https://drive.google.com/file/d/12qkiKi58KZaEnpLU9JJ7Vr4vveox8eCj/view?usp=sharing"}'::jsonb)
ON CONFLICT (activity_id) DO NOTHING;
