/*
  # Seed EM9_INT Daily Activities - Part 2 (Modules 3 & 4)

  1. New Data
    - `em_daily_activities`: ~30 activities for Modules 3 and 4
    - Covers investigations, FAL lessons, performance tasks, games, and post-assessments

  2. Notes
    - Module 3 focuses on Congruence and Rigid Motion with transformation explorations
    - Module 4 focuses on Reasoning with Linear Equations and systems
*/

-- Module 3 Activities
INSERT INTO em_daily_activities (activity_id, level_code, module_id, subtopic_id, day_number, activity_type, prompt_text, resource_urls) VALUES
  ('em9int_m3_d1_performance_task_00', 'EM9_INT', 'em9int_m3', 'em9int_m3_s1', 1, 'performance_task', 'Skateboarding Tricks', '{"task_paper": "https://drive.google.com/file/d/1GS_Ezh7162I6jmr1mzAUtpPF2AsruaOD/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/13wipHxWxcFSEZFBKmDy_9diI8tfBqH1sCD-diGNT5_U/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1O34Pu6A0_DrXbs5xdtTco55ExcvtUX7q/view?usp=sharing", "student_paced": "https://docs.google.com/presentation/d/15nErW-zFNmFvk0AqfN6w-uk6HsNFtutPn-zoCQHPpKM/copy?usp=sharing"}'::jsonb),
  ('em9int_m3_d1_fal_pre_assessment_01', 'EM9_INT', 'em9int_m3', 'em9int_m3_s3', 1, 'fal_pre_assessment', 'Pre-Assessment FAL — Transforming 2D Figures', '{"task_paper": "https://drive.google.com/file/d/15KtD26wEwDnArv-DAZZeSlBeMKOJDcn9/view?usp=sharing", "read_me": "https://docs.google.com/document/d/16FazudF7rEfZRo5N0FUl2urKCm6bK7riFfI5jn23i-M/copy?usp=sharing"}'::jsonb),
  ('em9int_m3_d2_investigation_02', 'EM9_INT', 'em9int_m3', 'em9int_m3_s2', 2, 'investigation', 'Transformations Introduction / Exploration 1 — Translation', '{"task_paper": "https://drive.google.com/file/d/1tj8BThp0VVqkAPzck6Vk7F9rEGlhyc-8/view?usp=drive_link", "full_lesson_slides": "https://docs.google.com/presentation/d/1PV4qcia-Yo7oJe5PM3C6DFmt8CWuzOMEiCM8o78dVnk/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1wTk_ANTtbD9njazmHxYfAJJEuzIH8EdV/view?usp=sharing", "self_paced": "https://docs.google.com/presentation/d/1X8H9hrKLh-dOilJOZKxBrztXr943FdPuPW0kWvN-Huw/copy?usp=sharing"}'::jsonb),
  ('em9int_m3_d3_investigation_03', 'EM9_INT', 'em9int_m3', 'em9int_m3_s2', 3, 'investigation', 'Transformations Exploration 2 (Translation) & Exploration 3 (Reflection)', '{"task_paper": "https://drive.google.com/file/d/1tj8BThp0VVqkAPzck6Vk7F9rEGlhyc-8/view?usp=drive_link", "full_lesson_slides": "https://docs.google.com/presentation/d/1WfXliRHdaHeVCpVqlEwRTPTCdXcQpWfgiA5FQNmh09g/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1-DIUpspRvytXZVoa5E6fDO9E94E519Ha/view?usp=sharing", "self_paced": "https://docs.google.com/presentation/d/17R57mdaje2wdY7yYzHWyTX7637RMSucHPk2nTKzlyS4/copy?usp=sharing"}'::jsonb),
  ('em9int_m3_d4_investigation_04', 'EM9_INT', 'em9int_m3', 'em9int_m3_s2', 4, 'investigation', 'Transformations Exploration 4 (Rotations) & Exploration 5', '{"task_paper": "https://drive.google.com/file/d/1tj8BThp0VVqkAPzck6Vk7F9rEGlhyc-8/view?usp=drive_link", "full_lesson_slides": "https://docs.google.com/presentation/d/1Co1RY890QqmbbHk63I0hcRqQR9aJiuS0ROEkHVDvbsE/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1I1gFFj2Z0SK1mEeNWiuq5bOh6gUnGp4r/view?usp=sharing", "self_paced": "https://docs.google.com/presentation/d/1AZ5EE35Af-_5hoqoEvb1J2cO50jLJaRb2VvI5-ya_Oo/copy?usp=sharing"}'::jsonb),
  ('em9int_m3_d5_investigation_05', 'EM9_INT', 'em9int_m3', 'em9int_m3_s2', 5, 'investigation', 'Transformations Exploration 6 — Review', '{"task_paper": "https://drive.google.com/file/d/1tj8BThp0VVqkAPzck6Vk7F9rEGlhyc-8/view?usp=drive_link", "full_lesson_slides": "https://docs.google.com/presentation/d/1wkrQU672A6BFFuAqm--YjlT4icVgmWnm2-qgecQbgLE/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/15BWl5DoQQkxj-Bs-nLjy82Px1MNieP59/view?usp=sharing", "self_paced": "https://docs.google.com/presentation/d/1gORwcV6ayrs1OJ2TTJW3sgdwSfrQ4DjCzJyEv0foC2A/copy?usp=sharing"}'::jsonb),
  ('em9int_m3_d5_performance_task_06', 'EM9_INT', 'em9int_m3', 'em9int_m3_s5', 5, 'performance_task', 'M.C. Escher (optional)', '{"task_paper": "https://drive.google.com/file/d/1cMZrqGUE2fcGpLH3ZyAFlVUWb5FYVi-g/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/1VzD4Oa5kEs41UJXhTxGkubcca9kux5CJ27DznCK2E-U/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/134YcSPXFcNdmmLbdEyyEltOj0dqmv59L/view?usp=sharing", "student_paced": "https://docs.google.com/presentation/d/192cdQvbVVAfX6OmsMa7JnbOlvUlI4D0F0hPrWPpXXFM/copy?usp=sharing"}'::jsonb),
  ('em9int_m3_d6_fal_lesson_07', 'EM9_INT', 'em9int_m3', 'em9int_m3_s3', 6, 'fal_lesson', 'FAL Transforming 2D Figures (Day 1)', '{"task_paper": "https://drive.google.com/file/d/15KtD26wEwDnArv-DAZZeSlBeMKOJDcn9/view?usp=sharing", "read_me": "https://docs.google.com/document/d/16FazudF7rEfZRo5N0FUl2urKCm6bK7riFfI5jn23i-M/copy?usp=sharing"}'::jsonb),
  ('em9int_m3_d7_fal_lesson_08', 'EM9_INT', 'em9int_m3', 'em9int_m3_s3', 7, 'fal_lesson', 'FAL Transforming 2D Figures (Day 2)', '{"task_paper": "https://drive.google.com/file/d/15KtD26wEwDnArv-DAZZeSlBeMKOJDcn9/view?usp=sharing", "read_me": "https://docs.google.com/document/d/16FazudF7rEfZRo5N0FUl2urKCm6bK7riFfI5jn23i-M/copy?usp=sharing"}'::jsonb),
  ('em9int_m3_d8_fal_post_assessment_09', 'EM9_INT', 'em9int_m3', 'em9int_m3_s3', 8, 'fal_post_assessment', 'FAL Transforming 2D Figures (Day 3 / Post Assessment)', '{"task_paper": "https://drive.google.com/file/d/15KtD26wEwDnArv-DAZZeSlBeMKOJDcn9/view?usp=sharing", "read_me": "https://docs.google.com/document/d/16FazudF7rEfZRo5N0FUl2urKCm6bK7riFfI5jn23i-M/copy?usp=sharing"}'::jsonb),
  ('em9int_m3_d9_performance_task_10', 'EM9_INT', 'em9int_m3', 'em9int_m3_s4', 9, 'performance_task', 'Rigid Motion', '{"task_paper": "https://drive.google.com/file/d/1YOGaR5CgYEc9Ej9JU3AiwE16LMyqYRTG/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/1fJLn7f0DWkn21pvCaanMCrwsSRmwgWhLrrywF3UalRQ/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1YOGaR5CgYEc9Ej9JU3AiwE16LMyqYRTG/view?usp=sharing", "student_paced": "https://docs.google.com/presentation/d/1T94dCxvPwrp8WQ6305OvH85mgC-Z6jas_L5zLcflj0I/copy?usp=sharing"}'::jsonb),
  ('em9int_m3_d9_performance_task_11', 'EM9_INT', 'em9int_m3', 'em9int_m3_s4', 9, 'performance_task', 'Transforming Triangles', '{"task_paper": "https://drive.google.com/file/d/1SToWHTa1RoojYDykqBubggF6_1KVQY7Q/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/18xqcFMXz8FAc2AKlHbFZgd-2ANgv23AAMWySVZc_SrY/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1SONztj6k3v_Wtmbh5xIS146V-VUBPbKp/view?usp=sharing", "student_paced": "https://docs.google.com/presentation/d/19748WIkh8Qv_NfCc4LGSj4enc6U-zaIVxp4A_kx_s4A/copy?usp=sharing"}'::jsonb),
  ('em9int_m3_d10_performance_task_12', 'EM9_INT', 'em9int_m3', 'em9int_m3_s5', 10, 'performance_task', 'Reflect & Rotate (optional)', '{"task_paper": "https://drive.google.com/file/d/1VrDYXloM_ryQXsKZ2Lv9Rfhzq52b0XLM/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/18ES6PzKllfPl0oMw23qT3Sp01qrF1OUq2ybLNxGE8mw/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/15p_JJf35jLPRnN3TgTXODN_v88avFGaH/view?usp=sharing", "student_paced": "https://docs.google.com/presentation/d/1lMAj_xtKmFevD4IFiuhcqubGowPx9mxdrw0qBzjDSMk/copy?usp=sharing"}'::jsonb),
  ('em9int_m3_d10_game_13', 'EM9_INT', 'em9int_m3', 'em9int_m3_s2', 10, 'game', 'Kahoot 1 — Transformations (optional)', '{"kahoot": "https://create.kahoot.it/share/transformations/dabe7f53-3c4d-4a07-b6a4-b1ad079b5c7e"}'::jsonb),
  ('em9int_m3_d10_game_14', 'EM9_INT', 'em9int_m3', 'em9int_m3_s2', 10, 'game', 'Kahoot 2 (optional)', '{"kahoot": "https://create.kahoot.it/share/transformations/7a7b1b68-79c6-4b40-8d39-4050629da8c0"}'::jsonb),
  ('em9int_m3_d10_post_assessment_15', 'EM9_INT', 'em9int_m3', NULL, 10, 'post_assessment', 'Grade 9 post-assessment', '{"faculty_portal": "http://svef.force.com/faculty"}'::jsonb)
ON CONFLICT (activity_id) DO NOTHING;

-- Module 4 Activities
INSERT INTO em_daily_activities (activity_id, level_code, module_id, subtopic_id, day_number, activity_type, prompt_text, resource_urls) VALUES
  ('em9int_m4_d1_fal_lesson_00', 'EM9_INT', 'em9int_m4', 'em9int_m4_s1', 1, 'fal_lesson', 'Launch — Solving Linear Equations (1 of 3)', '{"task_paper": "https://drive.google.com/file/d/1Uk6aDaXSffnDRnchYFc663jZexBNwO4B/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1oGPg3G2O94DrJJ8Layhl7k5f_wWXcTwRnX1W47QIIsY/copy?usp=sharing"}'::jsonb),
  ('em9int_m4_d3_fal_pre_assessment_01', 'EM9_INT', 'em9int_m4', 'em9int_m4_s2', 3, 'fal_pre_assessment', 'Pre-Assessment Core FAL — Classifying Solutions to Systems of Equations', '{"task_paper": "https://drive.google.com/file/d/1biD8br1FR5ril14Ow7xtLaMsJqnexyWc/view?usp=sharing", "pre_assess_slides": "https://docs.google.com/presentation/d/1qxZNxiwUFRLxdBJytiDcXb7i68m6NyqyV9GP-RdLkfs/copy?usp=sharing"}'::jsonb),
  ('em9int_m4_d3_fal_lesson_02', 'EM9_INT', 'em9int_m4', 'em9int_m4_s1', 3, 'fal_lesson', 'Launch — Solving Linear Equations (2 of 3)', '{"task_paper": "https://drive.google.com/file/d/1Uk6aDaXSffnDRnchYFc663jZexBNwO4B/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1oGPg3G2O94DrJJ8Layhl7k5f_wWXcTwRnX1W47QIIsY/copy?usp=sharing"}'::jsonb),
  ('em9int_m4_d4_fal_lesson_03', 'EM9_INT', 'em9int_m4', 'em9int_m4_s1', 4, 'fal_lesson', 'Launch — Solving Linear Equations (3 of 3)', '{"task_paper": "https://drive.google.com/file/d/1Uk6aDaXSffnDRnchYFc663jZexBNwO4B/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1oGPg3G2O94DrJJ8Layhl7k5f_wWXcTwRnX1W47QIIsY/copy?usp=sharing"}'::jsonb),
  ('em9int_m4_d5_performance_task_04', 'EM9_INT', 'em9int_m4', 'em9int_m4_s3', 5, 'performance_task', 'Words & Equations', '{"task_paper": "https://drive.google.com/file/d/1qe-FZMBPkcdq6NphgNKeOdFAxGoghG8d/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/1T7Xlq0u2hFawMJDlmTfrkQ2pIMv8UN4s7Jmf_oBbhcQ/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1QWPVorcpujNMsdBOhWWdoiE0Z361NFeC/view?usp=sharing"}'::jsonb),
  ('em9int_m4_d5_fal_lesson_05', 'EM9_INT', 'em9int_m4', 'em9int_m4_s1', 5, 'fal_lesson', 'Launch — Solving Linear Equations (buffer/if needed)', '{"task_paper": "https://drive.google.com/file/d/1Uk6aDaXSffnDRnchYFc663jZexBNwO4B/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1oGPg3G2O94DrJJ8Layhl7k5f_wWXcTwRnX1W47QIIsY/copy?usp=sharing"}'::jsonb),
  ('em9int_m4_d6_fal_lesson_06', 'EM9_INT', 'em9int_m4', 'em9int_m4_s2', 6, 'fal_lesson', 'Core FAL — Classifying Solutions to Systems of Equations (Day 1)', '{"task_paper": "https://drive.google.com/file/d/1biD8br1FR5ril14Ow7xtLaMsJqnexyWc/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1wjxiiT0g59hwFPVLivVYkViXYN_ptxB8pRMv1af7BUc/copy?usp=sharing"}'::jsonb),
  ('em9int_m4_d7_fal_lesson_07', 'EM9_INT', 'em9int_m4', 'em9int_m4_s2', 7, 'fal_lesson', 'Core FAL — Classifying Solutions to Systems of Equations (Day 2)', '{"task_paper": "https://drive.google.com/file/d/1biD8br1FR5ril14Ow7xtLaMsJqnexyWc/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1wjxiiT0g59hwFPVLivVYkViXYN_ptxB8pRMv1af7BUc/copy?usp=sharing"}'::jsonb),
  ('em9int_m4_d8_fal_lesson_08', 'EM9_INT', 'em9int_m4', 'em9int_m4_s2', 8, 'fal_lesson', 'Core FAL — Classifying Solutions to Systems of Equations (Day 3)', '{"task_paper": "https://drive.google.com/file/d/1biD8br1FR5ril14Ow7xtLaMsJqnexyWc/view?usp=sharing", "read_me": "https://docs.google.com/document/d/1wjxiiT0g59hwFPVLivVYkViXYN_ptxB8pRMv1af7BUc/copy?usp=sharing"}'::jsonb),
  ('em9int_m4_d9_performance_task_09', 'EM9_INT', 'em9int_m4', 'em9int_m4_s4', 9, 'performance_task', 'The Trip', '{"task_paper": "https://drive.google.com/file/d/16iiJfUqzeWLRMYFp44H9CUKd_U8EhUPC/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/1DBOzLO13HXCDno0Wjqy2f_fR23sAOvgw18m1O7TDvrg/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1AwhXhAd1aAPF9ZpZdmXh_WEtkLJFNZFc/view?usp=sharing", "self_paced": "https://docs.google.com/presentation/d/1K3SWTDez5lHn78b544z3vZdFQtcNtmUtB67pa0SSGjc/copy?usp=sharing"}'::jsonb),
  ('em9int_m4_d10_performance_task_10', 'EM9_INT', 'em9int_m4', 'em9int_m4_s4', 10, 'performance_task', 'Buying Chips and Candy', '{"task_paper": "https://drive.google.com/file/d/1_QkeducYJDfQ1nDSh8SgDF9Sa0LqKvUX/view?usp=sharing", "full_lesson_slides": "https://docs.google.com/presentation/d/1pJDpifKS3Lv6LI9q2bDlPP1gI3e0SynT1r6j2HXfbI4/copy?usp=sharing", "full_lesson_pdf": "https://drive.google.com/file/d/1BC6rp-DyP00VZSKGSEGFSVipL0mUqvKP/view?usp=sharing"}'::jsonb),
  ('em9int_m4_d10_post_assessment_11', 'EM9_INT', 'em9int_m4', NULL, 10, 'post_assessment', 'Grade 9 post-assessment', '{"faculty_portal": "http://svef.force.com/faculty"}'::jsonb)
ON CONFLICT (activity_id) DO NOTHING;
