/*
  # Student Name + Emoji Authentication

  Replaces number-based student IDs with First Name + Last Initial + Emoji identity.

  1. Schema Changes
    - `students.id` becomes auto-generated identity (no longer supplied by client)
    - Add `first_name` (text, letters only, required)
    - Add `last_initial` (single uppercase letter, required)
    - Add unique index on (teacher_username, lower(first_name), upper(last_initial), emoji_password)
      to handle duplicate-name resolution via emoji

  2. New Function
    - `register_or_login_student(p_teacher_username, p_first_name, p_last_initial, p_emoji_password, p_grade_level)`
      Creates or authenticates a student. Returns the student's id, or NULL if credentials don't match existing record.

  3. Notes
    - Drops obsolete `validate_and_create_student_record` function
    - Data is empty so changes are safe
*/

-- Drop obsolete function
DROP FUNCTION IF EXISTS validate_and_create_student_record(integer, text, text, text);

-- Add new columns
ALTER TABLE students ADD COLUMN IF NOT EXISTS first_name text;
ALTER TABLE students ADD COLUMN IF NOT EXISTS last_initial char(1);

-- Make id auto-generated (identity)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'public.students'::regclass
      AND attname = 'id'
      AND attidentity IN ('a','d')
  ) THEN
    ALTER TABLE students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- Add validation check constraints
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'students_first_name_letters_only'
  ) THEN
    ALTER TABLE students ADD CONSTRAINT students_first_name_letters_only
      CHECK (first_name IS NULL OR first_name ~ '^[A-Za-z]+$');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'students_last_initial_letter_only'
  ) THEN
    ALTER TABLE students ADD CONSTRAINT students_last_initial_letter_only
      CHECK (last_initial IS NULL OR last_initial ~ '^[A-Za-z]$');
  END IF;
END $$;

-- Unique identity index
CREATE UNIQUE INDEX IF NOT EXISTS students_identity_unique
  ON students (teacher_username, lower(first_name), upper(last_initial), emoji_password);

-- Helper index for lookups by teacher+name
CREATE INDEX IF NOT EXISTS students_teacher_name_idx
  ON students (teacher_username, lower(first_name), upper(last_initial));

-- Register/login RPC
CREATE OR REPLACE FUNCTION register_or_login_student(
  p_teacher_username text,
  p_first_name text,
  p_last_initial text,
  p_emoji_password text,
  p_grade_level text DEFAULT '6'
)
RETURNS TABLE(student_id integer, first_name text, last_initial char(1))
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_first text;
  v_initial char(1);
  v_existing_id integer;
  v_new_id integer;
  v_name_exists boolean;
BEGIN
  IF p_first_name IS NULL OR btrim(p_first_name) = '' THEN
    RAISE EXCEPTION 'First name is required';
  END IF;
  IF p_last_initial IS NULL OR btrim(p_last_initial) = '' THEN
    RAISE EXCEPTION 'Last initial is required';
  END IF;
  IF p_emoji_password IS NULL OR btrim(p_emoji_password) = '' THEN
    RAISE EXCEPTION 'Emoji password is required';
  END IF;
  IF p_first_name !~ '^[A-Za-z]+$' THEN
    RAISE EXCEPTION 'First name must contain only letters';
  END IF;
  IF p_last_initial !~ '^[A-Za-z]$' THEN
    RAISE EXCEPTION 'Last initial must be a single letter';
  END IF;

  v_first := initcap(lower(btrim(p_first_name)));
  v_initial := upper(btrim(p_last_initial));

  -- Exact match (teacher + first + initial + emoji) = authenticated
  SELECT s.id INTO v_existing_id
  FROM students s
  WHERE s.teacher_username = p_teacher_username
    AND lower(s.first_name) = lower(v_first)
    AND upper(s.last_initial) = v_initial
    AND s.emoji_password = p_emoji_password
  LIMIT 1;

  IF v_existing_id IS NOT NULL THEN
    UPDATE students SET last_seen = now() WHERE id = v_existing_id AND teacher_username = p_teacher_username;
    RETURN QUERY SELECT v_existing_id, v_first, v_initial;
    RETURN;
  END IF;

  -- Check if name exists under this teacher with a DIFFERENT emoji -> wrong password
  SELECT EXISTS (
    SELECT 1 FROM students s
    WHERE s.teacher_username = p_teacher_username
      AND lower(s.first_name) = lower(v_first)
      AND upper(s.last_initial) = v_initial
  ) INTO v_name_exists;

  IF v_name_exists THEN
    -- A student with this name exists but emoji doesn't match -> could be wrong password OR a new student sharing the name.
    -- Allow creation of a new record only if (name+emoji) combination is unique.
    IF EXISTS (
      SELECT 1 FROM students s
      WHERE s.teacher_username = p_teacher_username
        AND lower(s.first_name) = lower(v_first)
        AND upper(s.last_initial) = v_initial
        AND s.emoji_password = p_emoji_password
    ) THEN
      -- Shouldn't reach here since we already checked above
      RETURN;
    END IF;
    -- Create new record for same-name student with a different emoji
  END IF;

  -- Create new student
  INSERT INTO students (teacher_username, first_name, last_initial, emoji_password, grade_level)
  VALUES (p_teacher_username, v_first, v_initial, p_emoji_password, COALESCE(p_grade_level, '6'))
  RETURNING id INTO v_new_id;

  RETURN QUERY SELECT v_new_id, v_first, v_initial;
END;
$$;

GRANT EXECUTE ON FUNCTION register_or_login_student(text, text, text, text, text) TO anon, authenticated;
