/*
# Student Name + Emoji Authentication

Adds first_name and last_initial columns to the students table, and creates the
register_or_login_student RPC function for student login via name + emoji.

1. Schema Changes
  - Add `first_name` (text) to students
  - Add `last_initial` (char(1)) to students
  - Add unique identity index on (teacher_username, lower(first_name), upper(last_initial), emoji_password)

2. New Function
  - `register_or_login_student` - Creates or authenticates a student
    Returns student_id, first_name, last_initial

3. Security
  - Function is SECURITY DEFINER with search_path = public, extensions
  - Granted to anon and authenticated roles
*/

-- Add new columns
ALTER TABLE students ADD COLUMN IF NOT EXISTS first_name text;
ALTER TABLE students ADD COLUMN IF NOT EXISTS last_initial char(1);

-- Make id auto-generated (identity) if not already
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'public.students'::regclass
      AND attname = 'id'
      AND attidentity IN ('a','d')
  ) THEN
    ALTER TABLE students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- Add validation check constraints
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'students_first_name_letters_only'
  ) THEN
    ALTER TABLE students ADD CONSTRAINT students_first_name_letters_only
      CHECK (first_name IS NULL OR first_name ~ '^[A-Za-z]+$');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'students_last_initial_letter_only'
  ) THEN
    ALTER TABLE students ADD CONSTRAINT students_last_initial_letter_only
      CHECK (last_initial IS NULL OR last_initial ~ '^[A-Za-z]$');
  END IF;
END $$;

-- Unique identity index
CREATE UNIQUE INDEX IF NOT EXISTS students_identity_unique
  ON students (teacher_username, lower(first_name), upper(last_initial), emoji_password);

-- Helper index for lookups by teacher+name
CREATE INDEX IF NOT EXISTS students_teacher_name_idx
  ON students (teacher_username, lower(first_name), upper(last_initial));

-- Register/login RPC (uses the fixed version that rejects wrong emoji)
CREATE OR REPLACE FUNCTION register_or_login_student(
  p_teacher_username text,
  p_first_name text,
  p_last_initial text,
  p_emoji_password text,
  p_grade_level text DEFAULT '6'
)
RETURNS TABLE(student_id integer, first_name text, last_initial char(1))
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_first text;
  v_initial char(1);
  v_existing_id integer;
  v_new_id integer;
  v_name_exists boolean;
BEGIN
  -- Input validation
  IF p_first_name IS NULL OR btrim(p_first_name) = '' THEN
    RAISE EXCEPTION 'First name is required';
  END IF;
  IF p_last_initial IS NULL OR btrim(p_last_initial) = '' THEN
    RAISE EXCEPTION 'Last initial is required';
  END IF;
  IF p_emoji_password IS NULL OR btrim(p_emoji_password) = '' THEN
    RAISE EXCEPTION 'Emoji password is required';
  END IF;
  IF p_first_name !~ '^[A-Za-z]+$' THEN
    RAISE EXCEPTION 'First name must contain only letters';
  END IF;
  IF p_last_initial !~ '^[A-Za-z]$' THEN
    RAISE EXCEPTION 'Last initial must be a single letter';
  END IF;

  -- Normalize
  v_first := initcap(lower(btrim(p_first_name)));
  v_initial := upper(btrim(p_last_initial));

  -- Exact match (teacher + first + initial + emoji) = authenticated
  SELECT s.id INTO v_existing_id
  FROM students s
  WHERE s.teacher_username = p_teacher_username
    AND lower(s.first_name) = lower(v_first)
    AND upper(s.last_initial) = v_initial
    AND s.emoji_password = p_emoji_password
  LIMIT 1;

  IF v_existing_id IS NOT NULL THEN
    UPDATE students SET last_seen = now() WHERE id = v_existing_id AND teacher_username = p_teacher_username;
    RETURN QUERY SELECT v_existing_id, v_first, v_initial;
    RETURN;
  END IF;

  -- Check if name exists under this teacher (with ANY emoji)
  SELECT EXISTS (
    SELECT 1 FROM students s
    WHERE s.teacher_username = p_teacher_username
      AND lower(s.first_name) = lower(v_first)
      AND upper(s.last_initial) = v_initial
      AND s.emoji_password IS NOT NULL
      AND s.emoji_password != ''
  ) INTO v_name_exists;

  IF v_name_exists THEN
    -- Name exists but emoji doesn't match -> WRONG PASSWORD, reject login
    RAISE EXCEPTION 'Wrong emoji password. Please pick the emoji you chose when you first logged in.';
  END IF;

  -- Name does NOT exist at all -> first-time login, create new student
  INSERT INTO students (teacher_username, first_name, last_initial, emoji_password, grade_level)
  VALUES (p_teacher_username, v_first, v_initial, p_emoji_password, COALESCE(p_grade_level, '6'))
  RETURNING id INTO v_new_id;

  RETURN QUERY SELECT v_new_id, v_first, v_initial;
END;
$$;

GRANT EXECUTE ON FUNCTION register_or_login_student(text, text, text, text, text) TO anon, authenticated;
